apiVersion: v1
kind: Pod
metadata:
  name: test-gpu
spec:
  securityContext:
    runAsUser: 666
  containers:
  - name: test-gpu
    image: swiftdiaries/bench
    command: 
    - "/bin/bash"
    - "-c"
    - " python tf_cnn_benchmarks.py --device=gpu --model=alexnet --batch_size=32"
    resources:
      requests:
        alpha.kubernetes.io/nvidia-gpu: 1
      limits:
        alpha.kubernetes.io/nvidia-gpu: 1 
    volumeMounts:
    - name: nfs
      mountPath: "/mnt"
    - name: nvidia-driver-384-111
      mountPath: /usr/local/nvidia
      readOnly: true
    - name: libcuda-so
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
    - name: libcuda-so-1
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    - name: libcuda-so-384-111
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.384.111
      readOnly: true
  restartPolicy: Never
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs
  - name: nvidia-driver-384-111
    hostPath:
      path: /usr/lib/nvidia-384
  - name: libcuda-so
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so
  - name: libcuda-so-1
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
  - name: libcuda-so-384-111
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.384.111